# Generated by Django 4.1.7 on 2023-02-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productslistitem',
            options={'ordering': ('-recently_added', 'ordinal_number', '-created_at', 'product')},
        ),
        migrations.AddField(
            model_name='productslistitem',
            name='recently_added',
            field=models.BooleanField(default=True),
        ),
    ]
